[build]
target = "wasm32-unknown-emscripten"

[target.wasm32-unknown-emscripten]
rustflags = ["-C", "link-args=-sASYNCIFY -sASYNCIFY_IMPORTS=emscripten_asm_const_int_sync_on_main_thread -sEXPORTED_RUNTIME_METHODS=ccall -sFETCH -sFORCE_FILESYSTEM=1 -sALLOW_MEMORY_GROWTH=1 -lembind -pthread -o out/index.html", "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[unstable]
build-std = ["panic_abort", "std"]