[package]
name = "em-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
em-bindgen = { path = "..", features = ["fetch"] }
futures = { version = "0.3.30", features = ["executor"] }
http = "1.1.0"
log = "0.4.22"